# Generated by Django 6.0.3 on 2026-04-29 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_price_from_markup',
            field=models.BooleanField(default=True, help_text='If checked, price = cost * (1 + markup/100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Markup % applied to cost to get price', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.group'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['group'], name='inventory_p_group_i_f2a09e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'category')},
        ),
    ]
